version: '3.2'
services:
    jekyll:
        image: jekyll/jekyll
        entrypoint:
            - jekyll
            - serve
            - -s
            - /app
        volumes:
            - ".:/app/"
        ports:
            - "4000:4000"
